class constants(object):

    TOKEN = "Your Token"

    WEAPONS = {
        1:"Flatline",
        2:"R-301",
        3:"Hemlok",
        4:"G7-Scout",
        5:"Havoc",
        6:"Alternator",
        7:"Prowler",
        8:"R-99",
        9:"Volt",
        10:"Devotion",
        11:"Spitfire",
        12:"L-Star",
        13:"Longbow",
        14:"Kraber",
        15:"Triple Take",
        16:"Charge Rifle",
        17:"Sentinel",
        18:"EVA-8 Auto",
        19:"Mastiff",
        20:"Mozambique",
        21:"Peacekeeper",
        22:"RE-45",
        23:"P2020",
        24:"Wingman"
    }

    LEGENDS = {
        1:"Bloodhound",
        2:"Gibraltar",
        3:"Lifeline",
        4:"Pathfinder",
        5:"Wraith",
        6:"Bangalore",
        7:"Caustic",
        8:"Mirage",
        9:"Octane",
        10:"Wattson",
        11:"Crypto",
        12:"Revenant",
        13:"Loba",
        14:"Rampart",
        15:"Horizon"
    }

    HEROES = {
        1:{
            1:"D.VA",
            2:"Orisa",
            3:"Reinhardt",
            4:"Roadhog",
            5:"Sigma",
            6:"Winston",
            7:"Wrecking Ball",
            8:"Zarya",
        },
        2:{
            1:"Ashe",
            2:"Bastion",
            3:"Doomfist",
            4:"Echo",
            5:"Genji",
            6:"Hanzo",
            7:"Junkrat",
            8:"McCree",
            9:"Mei",
            10:"Pharah",
            11:"Reaper",
            12:"Soldier",
            13:"Sombra",
            14:"Symmetra",
            15:"Torbjörn",
            16:"Tracer",
            17:"Widowmaker",
        },
        3:{
            1:"Ana",
            2:"Baptiste",
            3:"Brigitte",
            4:"Lucio",
            5:"Mercy",
            6:"Moira",
            7:"Zenyatta",
        }
    }

    OWROLE = {
        1:"Tank",
        2:"Dps",
        3:"Support"
    }

    OPERATORS = {
        "att" : {
            1:"Glaz",
            2:"Fuze",
            3:"IQ",
            4:"Blitz",
            5:"Twitch",
            6:"Montagne",
            7:"Thermite",
            8:"Ash",
            9:"Thatcher",
            10:"Sledge",
            11:"Buck",
            12:"Blackbeard",
            13:"Capitao",
            14:"Hibana",
            15:"Jackal",
            16:"Ying",
            17:"Zofia",
            18:"Dokkaebi",
            19:"Finka",
            20:"Lion",
            21:"Maverick",
            22:"Nomad",
            23:"Gridlock",
            24:"NØKK",
            25:"Amaru",
            26:"Kali",
            27:"Iana",
            28:"Ace",
            29:"Zero",
        },
        "def":{
            1:"Kapkan",
            2:"Tachanka",
            3:"Bandit",
            4:"Jäger",
            5:"Rook",
            6:"Doc",
            7:"Pulse",
            8:"Castle",
            9:"Smoke",
            10:"Mute",
            11:"Frost",
            12:"Valkyrie",
            13:"Caveira",
            14:"Echo",
            15:"Mira",
            16:"Lesion",
            17:"Ela",
            18:"Vigil",
            19:"Alibi",
            20:"Maestro",
            21:"Clash",
            22:"Kaid",
            23:"Mozzie",
            24:"Warden",
            25:"Goyo",
            26:"Wamai",
            27:"Oryx",
            28:"Melusi",
            29:"Aruni",
        },
    }

    CHAMPIONS = {
            1 : "Aatrox",
            2 : "Ahri",
            3 : "Akali",
            4 : "Alistar",
            5 : "Amumu",
            6 : "Anivia",
            7 : "Annie",
            8 : "Aphelios",
            9 : "Ashe",
            10 : "AurelionSol",
            11 : "Azir",
            12 : "Bard",
            13 : "Blitzcrank",
            14 : "Brand",
            15 : "Braum",
            16 : "Caitlyn",
            17 : "Camille",
            18 : "Cassiopeia",
            19 : "Chogath",
            20 : "Corki",
            21 : "Darius",
            22 : "Diana",
            23 : "Draven",
            24 : "DrMundo",
            25 : "Ekko",
            26 : "Elise",
            27 : "Evelynn",
            28 : "Ezreal",
            29 : "Fiddlesticks",
            30 : "Fiora",
            31 : "Fizz",
            32 : "Galio",
            33 : "Gangplank",
            34 : "Garen",
            35 : "Gnar",
            36 : "Gragas",
            37 : "Graves",
            38 : "Hecarim",
            39 : "Heimerdinger",
            40 : "Illaoi",
            41 : "Irelia",
            42 : "Ivern",
            43 : "Janna",
            44 : "JarvanIV",
            45 : "Jax",
            46 : "Jayce",
            47 : "Jhin",
            48 : "Jinx",
            49 : "Kaisa",
            50 : "Kalista",
            51 : "Karma",
            52 : "Karthus",
            53 : "Kassadin",
            54 : "Katarina",
            55 : "Kayle",
            56 : "Kayn",
            57 : "Kennen",
            58 : "Khazix",
            59 : "Kindred",
            60 : "Kled",
            61 : "KogMaw",
            62 : "Leblanc",
            63 : "LeeSin",
            64 : "Leona",
            65 : "Lillia",
            66 : "Lissandra",
            67 : "Lucian",
            68 : "Lulu",
            69 : "Lux",
            70 : "Malphite",
            71 : "Malzahar",
            72 : "Maokai",
            73 : "MasterYi",
            74 : "MissFortune",
            75 : "MonkeyKing",
            76 : "Mordekaiser",
            77 : "Morgana",
            78 : "Nami",
            79 : "Nasus",
            80 : "Nautilus",
            81 : "Neeko",
            82 : "Nidalee",
            83 : "Nocturne",
            84 : "Nunu",
            85 : "Olaf",
            86 : "Orianna",
            87 : "Ornn",
            88 : "Pantheon",
            89 : "Poppy",
            90 : "Pyke",
            91 : "Qiyana",
            92 : "Quinn",
            93 : "Rakan",
            94 : "Rammus",
            95 : "RekSai",
            96 : "Renekton",
            97 : "Rengar",
            98 : "Riven",
            99 : "Rumble",
            100 : "Ryze",
            101 : "Samira",
            102 : "Sejuani",
            103 : "Senna",
            104 : "Seraphine",
            105 : "Sett",
            106 : "Shaco",
            107 : "Shen",
            108 : "Shyvana",
            109 : "Singed",
            110 : "Sion",
            111 : "Sivir",
            112 : "Skarner",
            113 : "Sona",
            114 : "Soraka",
            115 : "Swain",
            116 : "Sylas",
            117 : "Syndra",
            118 : "TahmKench",
            119 : "Taliyah",
            120 : "Talon",
            121 : "Taric",
            122 : "Teemo",
            123 : "Thresh",
            124 : "Tristana",
            125 : "Trundle",
            126 : "Tryndamere",
            127 : "TwistedFate",
            128 : "Twitch",
            129 : "Udyr",
            130 : "Urgot",
            131 : "Varus",
            132 : "Vayne",
            133 : "Veigar",
            134 : "Velkoz",
            135 : "Vi",
            136 : "Viktor",
            137 : "Vladimir",
            138 : "Volibear",
            139 : "Warwick",
            140 : "Xayah",
            141 : "Xerath",
            142 : "XinZhao",
            143 : "Yasuo",
            144 : "Yone",
            145 : "Yorick",
            146 : "Yuumi",
            147 : "Zac",
            148 : "Zed",
            149 : "Ziggs",
            150 : "Zilean",
            151 : "Zoe",
            152 : "Zyra",
    }